const CDP='http://127.0.0.1:9222'
const ver=await(await fetch(`${CDP}/json/version`)).json()
const ws=new WebSocket(ver.webSocketDebuggerUrl)
let id=0;const p=new Map()
const send=(m,pr={},s)=>new Promise((res,rej)=>{const i=++id;p.set(i,{res,rej});ws.send(JSON.stringify({id:i,method:m,params:pr,sessionId:s}))})
await new Promise(r=>ws.onopen=r)
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&p.has(m.id)){const{res,rej}=p.get(m.id);p.delete(m.id);m.error?rej(new Error(m.error.message)):res(m.result)}}
const{targetId}=await send('Target.createTarget',{url:'about:blank'})
const{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true})
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false},sessionId)
await send('Page.navigate',{url:process.argv[2]},sessionId)
await new Promise(r=>setTimeout(r,3000))
const{result}=await send('Runtime.evaluate',{expression:`JSON.stringify(['.heat-panel','.heat-filters','.cards','.count-num','.overview'].map(s=>{const el=document.querySelector(s);if(!el)return[s,null];const r=el.getBoundingClientRect();return[s,Math.round(r.top+scrollY),Math.round(r.height)]}))`,returnByValue:true},sessionId)
console.log(result.value)
await send('Target.closeTarget',{targetId});ws.close();process.exit(0)
