// node shotclick.mjs <url> <width> <out> <chipLabel> <clipY:clipH>
const [url,wS,out,label,clip]=process.argv.slice(2)
const width=Number(wS)
const CDP='http://127.0.0.1:9222'
const ver=await(await fetch(`${CDP}/json/version`)).json()
const ws=new WebSocket(ver.webSocketDebuggerUrl)
let id=0;const p=new Map()
const send=(m,pr={},s)=>new Promise((res,rej)=>{const i=++id;p.set(i,{res,rej});ws.send(JSON.stringify({id:i,method:m,params:pr,sessionId:s}))})
await new Promise(r=>ws.onopen=r)
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&p.has(m.id)){const{res,rej}=p.get(m.id);p.delete(m.id);m.error?rej(new Error(m.error.message)):res(m.result)}}
const{targetId}=await send('Target.createTarget',{url:'about:blank'})
const{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true})
await send('Page.enable',{},sessionId)
await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:2,mobile:width<600},sessionId)
await send('Page.navigate',{url},sessionId)
await new Promise(r=>setTimeout(r,3000))
await send('Runtime.evaluate',{expression:`[...document.querySelectorAll('.heat-chip')].find(b=>b.textContent.trim()==='${label}')?.click()`},sessionId)
await new Promise(r=>setTimeout(r,900))
const[y,h]=clip.split(':').map(Number)
const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y,width,height:h,scale:1}},sessionId)
const fs=await import('node:fs');fs.writeFileSync(out,Buffer.from(data,'base64'))
await send('Target.closeTarget',{targetId});ws.close();console.log('WROTE',out);process.exit(0)
